config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'events#index'
  
  devise_for :users
  resource :user, only: :show, as: :profile
  resources :users, only: :show
  
  get 'about', to: 'application#about'
  
  resources :events do
    resource :invitations, only: [:new, :edit, :update, :create]
  end

  resources :invitations, only: [] do
    member do
      post 'accept'
      post 'pend'
      post 'decline'
    end
  end
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id          :bigint           not null, primary key
#  name        :string           not null
#  date        :datetime         not null
#  location    :string           not null
#  description :text
#  host_id     :bigint           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Event < ApplicationRecord
  validates :name, :date, :location, presence: true
  validates :name, uniqueness: true
  validate :starts_in_the_future, if: -> { date }

  belongs_to :host, class_name: :User

  has_many :invitations, dependent: :destroy

  has_many :confirmations,
    -> { where rsvp: 'ACCEPTED' },
    class_name: :Invitation,
    inverse_of: :event

  has_many :guests,
    -> { order(:username) },
    through: :confirmations,
    source: :recipient

  scope :upcoming, -> { where('date > ?', Time.now) }
  scope :past, -> { where('date < ?', Time.now) }

  def host_name
    host.username
  end

  def date_and_time
    date.strftime('%b %-d %Y %l:%M%P')
  end

  def date_only
    date.strftime('%b %-d %Y')
  end

  private

  def starts_in_the_future
    if date < Date.current
      errors.add(:base, :blank, message: 'Event date must be in the future.')
    end
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :require_host!, except: [:index, :show, :new, :create]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event.guests.load
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = current_user.events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to new_event_invitations_url(@event), notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Event was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:name, :date, :location, :description)
    end

    def require_host!
      unless current_user == @event.host
        flash[:alert] = 'You are not authorized to edit this event!'
        redirect_to root_url
      end
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<div class='event <%= 'past' unless upcoming %>'>
  <div class='name'><%= event.name %></div>
  <div class='basic-info'>
    <%= event.date_and_time %> •
    <%= event.location %>
  </div>
<a href='<%= event_path(event) %>' class='show-link'>
  <div>Info</div>
</a>
</div>

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%#= form.label :name %>
    <!-- use raw html so field-with-error class is not applied -->
    <label for='event_name'>Name</label>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <label for='event_date'>Date</label>
    <%= form.datetime_select :date %>
  </div>

  <div class="field">
    <label for='event_location'>Location</label>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, rows: '10', cols: '35' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'important-button' %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<div class='end-link'>
  <%= link_to 'Cancel', @event %> |
  <%= link_to 'Home', events_path %>
</div>

app/views/events/index.html.erb
<div class='page-title-container'>
  <h1>Odin Events</h1>
</div>

<div class='events-container'>
  <h3 class='event-category'>Upcoming Events</h3>
  <%= render @events.upcoming.order(:date), upcoming: true %>
  <h3 class='event-category'>Past Events</h3>
  <%= render @events.past.order(date: :desc), upcoming: false %>
</div>

app/views/events/index0.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Date</th>
      <th>Location</th>
      <th>Description</th>
      <th>Host</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.includes(:host).each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.date_only %></td>
        <td><%= event.location %></td>
        <td><%= event.description %></td>
        <td><%= event.host.username %></td>
        <td><%= link_to 'Show', event %></td>
        <% if event.host == current_user %>
          <td><%= link_to 'Edit', edit_event_path(event) %></td>
          <td><%= link_to 'Delete', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Cancel', @event, class: 'end-link' %>

app/views/events/show.html.erb
<div class='event-show'>
  <div class='name-show'><%= @event.name %></div>
  <div class='basic-info-show'>
    <%= @event.date_and_time %> •
    <%= @event.location %> •
    Hosted by <%= @event.host_name %>
  </div>
  <div class='description'><%= @event.description %></div>
  <hr class='event-show-line'>
  <div>
    <div class='list-category'>Confirmed Guests: (<%= @event.guests.length %>)</div>
    <% @event.guests.each do |guest| %>
      <div class='ACCEPTED invitation-list-item'>
        <li><%= link_to guest.username, guest %></li>
        <i class="fas fa-check"></i>
      </div>
    <% end %>
  </div>
  <div>
    <div class='list-category'>All Invitations: (<%= @event.invitations.count %>)</div>
    <% @event.invitations.includes(:recipient).order(:username).references(:recipient).each do |invitation| %>
      <div class="invitation-list-item <%= invitation.rsvp %>">
        <li><%= link_to invitation.recipient.username, user_path(invitation.recipient) %></li>
        <% if invitation.rsvp == 'ACCEPTED' %>
          <i class="fas fa-check"></i>
        <% elsif invitation.rsvp == 'PENDING' %>
          <i class="far fa-clock"></i>
        <% else %>
          <i class="fas fa-times"></i>
        <% end %>
      </div>
    <% end %>
  </div>
  <% if current_user == @event.host %>
    <div>
      <%= link_to 'Edit', edit_event_path(@event) %> |
      <%= link_to 'Update Invitations', edit_event_invitations_path(@event) %> |
      <%= link_to 'Delete Event', event_path(@event), method: :delete, data: { confirm: 'Are you sure?'} %>
    </div>
  <% end %>
</div>

<br>
<%= link_to 'Back', events_path, class: 'end-link' %>