config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'events#index'
  
  devise_for :users
  resource :user, only: :show, as: :profile
  resources :users, only: :show
  
  get 'about', to: 'application#about'
  
  resources :events do
    resource :invitations, only: [:new, :edit, :update, :create]
  end

  resources :invitations, only: [] do
    member do
      post 'accept'
      post 'pend'
      post 'decline'
    end
  end
end

app/models/invitation.rb
# == Schema Information
#
# Table name: invitations
#
#  id           :bigint           not null, primary key
#  rsvp         :string           default("PENDING"), not null
#  event_id     :bigint           not null
#  recipient_id :bigint           not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
class Invitation < ApplicationRecord
  after_initialize :ensure_rsvp

  validates :rsvp, presence: true
  validates :rsvp, inclusion: { in: %w[ACCEPTED PENDING DECLINED] }, if: -> { rsvp }
  validates :event_id, uniqueness: { scope: :recipient_id }
  validate :no_host_invite, if: -> { event }

  belongs_to :event
  belongs_to :recipient, class_name: :User

  scope :upcoming, -> { joins(:event).merge(Event.upcoming) }
  scope :past, -> { joins(:event).merge(Event.past) }

  def accepted?
    rsvp == 'ACCEPTED'
  end

  def accept!
    update(rsvp: 'ACCEPTED')
  end

  def decline!
    update(rsvp: 'DECLINED')
  end

  def recipient_name
    recipient.username
  end

  private

  def ensure_rsvp
    rsvp ||= 'PENDING'
  end

  def no_host_invite
    event = Event.find(event_id)
    if event.host_id == recipient_id
      errors.add(:base, 'Host cannot invite themself')
    end
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_action :authenticate_user!

  before_action :set_event, only: [:new, :create, :edit, :update]
  before_action :require_host!, only: [:new, :create, :edit, :update]

  before_action :set_invitation, only: [:accept, :pend, :decline]
  before_action :require_recipient!, only: [:accept, :pend, :decline]

  def new
    render :new
  end

  def create
    params[:recipient].select { |_k, v| v == '1' }.keys.map(&:to_i).each do |user_id|
      @event.invitations.find_or_create_by(recipient_id: user_id)
    end
    redirect_to event_url(@event)
  end

  def edit
    if @event.date < Time.now
      flash.notice = 'You cannot update invitations for past events.'
      redirect_to @event
    else
      render :edit
    end
  end

  def update
    no_uninvites = []
    params[:recipient].each do |user_id, value|
      if value == '1'
        @event.invitations.find_or_create_by(recipient_id: user_id.to_i)
      else
        invitation = @event.invitations.includes(:recipient).find_by(recipient_id: user_id.to_i)
        if invitation
          if invitation.rsvp == 'ACCEPTED'
            no_uninvites << invitation.recipient_name
          else
            invitation.destroy
          end
        end
      end
    end
    flash.notice = "The following guests have already commited and cannot be uninvited: #{no_uninvites.join(', ')}." unless no_uninvites.empty?
    redirect_to event_url(@event)
  end

  def accept
    @invitation.update(rsvp: 'ACCEPTED')
    redirect_to profile_path(anchor: 'invitations')
  end

  def pend
    @invitation.update(rsvp: 'PENDING')
    redirect_to profile_path(anchor: 'invitations')
  end

  def decline
    @invitation.update(rsvp: 'DECLINED')
    redirect_to profile_path(anchor: 'invitations')
  end

  private

  def invitation_params
    params.require(:invitation).permit(:event_id, :recipient_id)
  end

  def set_invitation
    @invitation = Invitation.find(params[:id])
  end

  def set_event
    @event = Event.find(params[:event_id])
  end

  def require_host!
    unless current_user == @event.host
      flash[:alert] = 'You are not authorized to edit invitations for this event!'
      redirect_to root_url
    end
  end

  def require_recipient!
    unless current_user == @invitation.recipient
      flash[:alert] = 'You are not authorized to respond to this invitation!'
      redirect_to root_url
    end
  end
end

app/views/invitations/_invitation.html.erb
<div class='invitation <%= 'past' unless upcoming %>'>
  <div class='invitation-name'><%= link_to invitation.event.name, event_path(invitation.event) %></div>
  <div class='invitation-date'><%= invitation.event.date_only %></div>
  <div class='rsvp-actions'>
    <% if upcoming %>
      <% if invitation.rsvp == 'ACCEPTED' %>
        <%= button_to 'Attending', pend_invitation_path(invitation), class: 'current-status rsvp' %>
        <%= button_to 'Declined', decline_invitation_path(invitation), class: 'rsvp' %>
      <% elsif invitation.rsvp == 'DECLINED' %>
        <%= button_to 'Attending', accept_invitation_path(invitation), class: 'rsvp' %>
        <%= button_to 'Declined', pend_invitation_path(invitation), class: 'current-status rsvp' %>
      <% else %>
        <%= button_to 'Attending', accept_invitation_path(invitation), class: 'rsvp' %>
        <%= button_to 'Declined', decline_invitation_path(invitation), class: 'rsvp' %>
      <% end %>
    <% else %>
      <% if invitation.rsvp == 'ACCEPTED' %>
        <div class='past-status past-action'>Attended</div>
        <div class='past-action'>Declined</div>
      <% elsif invitation.rsvp == 'DECLINED' %>
        <div class='past-action'>Attended</div>
        <div class='past-status past-action'>Declined</div>
      <% else %>
        <div class='past-action'>Attended</div>
        <div class='past-action'>Declined</div>
      <% end %>
    <% end %>
  </div>


</div>

app/views/invitations/edit.html.erb
<h4><%= @event.name %></h4>

<p>Update your invitation list.</p>


<%= form_with(url: event_invitations_path(@event), method: :patch, local: true) do |f| %>
  <%= hidden_field_tag(:event_id, @event.id) %>

  <% temp_invitations = @event.invitations.pluck(:recipient_id) %>
  <% User.order(:username).each do |user| %>
    <% next if user == @event.host %>
    <div class='checkbox'>
      <%= f.check_box("recipient[#{user.id}]", { checked: !!temp_invitations.delete(user.id) } ) %>
      <%= f.label "recipient[#{user.id}]", user.username %>
    </div>
  <% end %>
  <br>
  <%= submit_tag('Update Invitations!', class: 'important-button') %>
<% end %>

<br>
<div class='end-link'>
  <%= link_to 'Cancel', @event %> |
  <%= link_to 'Home', events_path %>
</div>

app/views/invitations/new.html.erb
<h4><%= @event.name %></h4>

<p>You're almost done! Now it's time to invite some guests!</p>


<%= form_with(url: event_invitations_path(@event), local: true) do |f| %>
  <%= hidden_field_tag(:event_id, @event.id) %>

  <% User.order(:username).each do |user| %>
    <% next if user == @event.host %>
    <div class='checkbox'>
      <%= f.check_box("recipient[#{user.id}]") %>
      <%= f.label "recipient[#{user.id}]", user.username %>
    </div>
  <% end %>
  <br>
  <%= submit_tag('Invite Guests!', class: 'important-button') %>
<% end %>

<br>
<%= link_to 'Now now', profile_path, class: 'end-link' %>