config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'events#index'
  
  devise_for :users
  resource :user, only: :show, as: :profile
  resources :users, only: :show
  
  get 'about', to: 'application#about'
  
  resources :events do
    resource :invitations, only: [:new, :edit, :update, :create]
  end

  resources :invitations, only: [] do
    member do
      post 'accept'
      post 'pend'
      post 'decline'
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/07b0558508.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css2?family=Piazzolla:ital,wght@1,600&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=PT+Sans:ital@0;1&display=swap" rel="stylesheet">  </head>

  <body>
    <header>
      <div class='header-left'>
        <button class='header-button border-right'>
          <%= link_to 'Home', root_path, class: 'header-item' %>
        </button><!--
        --><button class='header-button border-right'>
          <%= link_to 'About', about_path, class: 'header-item' %>
        </button>
      </div>
      <div class='header-right'>
        <button class='header-button border-right border-left'>
          <%= link_to 'New Event', new_event_path, class: 'header-item' %>
        </button><!--
        <% if user_signed_in? %>
          --><button class='header-button border-right'>
            <%= link_to current_user.username, profile_path, class: 'header-item' %>
          </button><!--
          --><button class='header-button'>
            <%= link_to 'Logout', destroy_user_session_path, class: 'header-item', method: :delete %>
          </button>
        <% else %>
          --><button class='header-button border-right'>
            <%= link_to 'Login', new_user_session_path, class: 'header-item' %>
          </button><!--
          --><button class='header-button'>
            <%= link_to 'Sign Up', new_user_registration_path, class: 'header-item' %>
          </button>
        <% end %>
      </div>
    </header>
    <% if notice || alert %>
      <div class='flash-container'>
        <% if notice %>
          <div id="notice"><%= notice %></div>
        <% end %>
        <% if alert %>
          <div class="alert"><%= alert %></div>
        <% end %>
      </div>
    <% end %>
    <div class='page-body'>
      <%= yield %>
    </div>
  </body>
</html>